---
# file: roles/common/tasks/reboot.yml
- name: reboot
  shell: nohup bash -c "sleep 2s && reboot" &

- name: wait for the server to go down (reboot)
  local_action:
    "wait_for host={{ inventory_hostname }} port=22 state=stopped"

- name: wait for the server to come up
  local_action:
    "wait_for host={{ inventory_hostname }} port=22 state=started timeout=600"
