---
# file: roles/common/handlers/main.yml
- name: ntpd restart
  service:
    name: ntpd
    state: restarted

- name: chronyd restart
  service:
    name: chronyd
    state: restarted

- name: systemd-journald restart
  service:
    name: systemd-journald.service
    state: restarted

- name: rsyslog restart
  service:
    name: rsyslog.service
    state: restarted

- name: abrtd restart
  service:
    name: abrtd.service
    state: restarted

- name: kdump restart
  service:
    name: kdump.service
    state: restarted
