---
# file: roles/vsftpd/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - vsftpd

- name: add vsftpd settings
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd/vsftpd.conf owner=root group=root mode=0600 backup=true
  register: is_vsftpd_setting

- name: backup vsftpd setting
  fetch:
    src={{item}}
    dest="backup/{{ansible_date_time.date}}-{{ansible_date_time.time|regex_replace(':', '')}}"
  with_items:
    - "{{is_vsftpd_setting.backup_file}}"
    - /etc/vsftpd/vsftpd.conf
  when: is_vsftpd_setting|changed

- name: delete vsftpd setting backup
  file: path={{is_vsftpd_setting.backup_file}} state=absent
  when: is_vsftpd_setting|changed and is_vsftpd_setting.backup_file is defined

- name: add vsftpd pam.d settings
  template: src=vsftpd.virtual.j2 dest=/etc/pam.d/vsftpd.virtual owner=root group=root mode=0644 backup=true
  register: is_vsftpd_pam_d_setting

- name: backup vsftpd pam.d setting
  fetch:
    src={{item}}
    dest="backup/{{ansible_date_time.date}}-{{ansible_date_time.time|regex_replace(':', '')}}"
  with_items:
    - "{{is_vsftpd_pam.d_setting.backup_file}}"
    - /etc/pam.d/vsftpd.virtual
  when: is_vsftpd_pam_d_setting|changed

- name: delete vsftpd pam.d setting backup
  file: path={{is_vsftpd_pam.d_setting.backup_file}} state=absent
  when: is_vsftpd_pam_d_setting|changed and is_vsftpd_pam_d_setting.backup_file is defined
